gazebo_ros_control:
  pid_gains:
    joint1: {p: 2.0, i: 0.05, d: 0.0}
    joint2: {p: 2.0, i: 0.05, d: 0.0}
    joint3: {p: 2.0, i: 0.05, d: 0.0}
    joint4: {p: 2.0, i: 0.05, d: 0.0}
    joint5: {p: 2.0, i: 0.05, d: 0.0}
    r_joint: {p: 0.3, i: 0.01, d: 0.0}
