global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 1
  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  inflation_layer:
    enabled: true
    inflation_radius: 0.25 # Distance minimale entre le robot et un obstacle en planification globale (doit être ≥ au rayon du robot).
    cost_scaling_factor: 10.0 # Facteur de pondération des coûts : plus il est élevé, plus la zone d’inflation autour des obstacles est réduite.
