# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.jetauto = QtWidgets.QWidget()
        self.jetauto.setObjectName("jetauto")
        self.horloge_group = QtWidgets.QGroupBox(self.jetauto)
        self.horloge_group.setGeometry(QtCore.QRect(60, 70, 341, 231))
        self.horloge_group.setAlignment(QtCore.Qt.AlignCenter)
        self.horloge_group.setObjectName("horloge_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.horloge_group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.horloge_group)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.horloge_group)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.Button_check_date = QtWidgets.QPushButton(self.horloge_group)
        self.Button_check_date.setObjectName("Button_check_date")
        self.gridLayout_2.addWidget(self.Button_check_date, 2, 0, 1, 1)
        self.tf_odom_horloge = QtWidgets.QGroupBox(self.jetauto)
        self.tf_odom_horloge.setGeometry(QtCore.QRect(520, 70, 351, 231))
        self.tf_odom_horloge.setAlignment(QtCore.Qt.AlignCenter)
        self.tf_odom_horloge.setObjectName("tf_odom_horloge")
        self.button_launc_tf_odom = QtWidgets.QPushButton(self.tf_odom_horloge)
        self.button_launc_tf_odom.setGeometry(QtCore.QRect(130, 60, 89, 25))
        self.button_launc_tf_odom.setObjectName("button_launc_tf_odom")
        self.label_status_tf_odom = QtWidgets.QLabel(self.tf_odom_horloge)
        self.label_status_tf_odom.setGeometry(QtCore.QRect(40, 120, 67, 17))
        self.label_status_tf_odom.setObjectName("label_status_tf_odom")
        self.ssh_group = QtWidgets.QGroupBox(self.jetauto)
        self.ssh_group.setGeometry(QtCore.QRect(270, 340, 381, 221))
        self.ssh_group.setAlignment(QtCore.Qt.AlignCenter)
        self.ssh_group.setObjectName("ssh_group")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.ssh_group)
        self.buttonBox.setGeometry(QtCore.QRect(150, 110, 80, 25))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.buttonBox.setObjectName("buttonBox")
        self.tf_odom_horloge.raise_()
        self.ssh_group.raise_()
        self.horloge_group.raise_()
        self.tabWidget.addTab(self.jetauto, "")
        self.navigation = QtWidgets.QWidget()
        self.navigation.setObjectName("navigation")
        self.cmdvel_group = QtWidgets.QGroupBox(self.navigation)
        self.cmdvel_group.setGeometry(QtCore.QRect(40, 30, 351, 301))
        self.cmdvel_group.setAlignment(QtCore.Qt.AlignCenter)
        self.cmdvel_group.setObjectName("cmdvel_group")
        self.forward_but = QtWidgets.QPushButton(self.cmdvel_group)
        self.forward_but.setGeometry(QtCore.QRect(130, 60, 89, 25))
        self.forward_but.setObjectName("forward_but")
        self.backward_but = QtWidgets.QPushButton(self.cmdvel_group)
        self.backward_but.setGeometry(QtCore.QRect(130, 140, 89, 25))
        self.backward_but.setObjectName("backward_but")
        self.left_but = QtWidgets.QPushButton(self.cmdvel_group)
        self.left_but.setGeometry(QtCore.QRect(30, 100, 89, 25))
        self.left_but.setObjectName("left_but")
        self.right_but = QtWidgets.QPushButton(self.cmdvel_group)
        self.right_but.setGeometry(QtCore.QRect(220, 100, 89, 25))
        self.right_but.setObjectName("right_but")
        self.stop_but = QtWidgets.QPushButton(self.cmdvel_group)
        self.stop_but.setGeometry(QtCore.QRect(140, 100, 61, 25))
        self.stop_but.setObjectName("stop_but")
        self.omni_left_but = QtWidgets.QPushButton(self.cmdvel_group)
        self.omni_left_but.setGeometry(QtCore.QRect(20, 200, 89, 25))
        self.omni_left_but.setObjectName("omni_left_but")
        self.omni_right_but = QtWidgets.QPushButton(self.cmdvel_group)
        self.omni_right_but.setGeometry(QtCore.QRect(230, 200, 89, 25))
        self.omni_right_but.setObjectName("omni_right_but")
        self.vitesse_label = QtWidgets.QLabel(self.cmdvel_group)
        self.vitesse_label.setGeometry(QtCore.QRect(130, 250, 67, 17))
        self.vitesse_label.setObjectName("vitesse_label")
        self.label_vitesse_cmdvel = QtWidgets.QLabel(self.cmdvel_group)
        self.label_vitesse_cmdvel.setGeometry(QtCore.QRect(190, 250, 67, 17))
        self.label_vitesse_cmdvel.setObjectName("label_vitesse_cmdvel")
        self.amcl_group = QtWidgets.QGroupBox(self.navigation)
        self.amcl_group.setGeometry(QtCore.QRect(40, 360, 351, 221))
        self.amcl_group.setAlignment(QtCore.Qt.AlignCenter)
        self.amcl_group.setObjectName("amcl_group")
        self.button_check_pose = QtWidgets.QPushButton(self.amcl_group)
        self.button_check_pose.setGeometry(QtCore.QRect(50, 50, 106, 25))
        self.button_check_pose.setObjectName("button_check_pose")
        self.button_reset_pose = QtWidgets.QPushButton(self.amcl_group)
        self.button_reset_pose.setGeometry(QtCore.QRect(200, 50, 89, 25))
        self.button_reset_pose.setObjectName("button_reset_pose")
        self.label_pose = QtWidgets.QLabel(self.amcl_group)
        self.label_pose.setGeometry(QtCore.QRect(140, 90, 60, 17))
        self.label_pose.setObjectName("label_pose")
        self.label_pose_amcl = QtWidgets.QLabel(self.amcl_group)
        self.label_pose_amcl.setGeometry(QtCore.QRect(120, 140, 101, 51))
        self.label_pose_amcl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pose_amcl.setObjectName("label_pose_amcl")
        self.goal_group = QtWidgets.QGroupBox(self.navigation)
        self.goal_group.setGeometry(QtCore.QRect(540, 360, 361, 221))
        self.goal_group.setAlignment(QtCore.Qt.AlignCenter)
        self.goal_group.setObjectName("goal_group")
        self.lineEdit_x = QtWidgets.QLineEdit(self.goal_group)
        self.lineEdit_x.setGeometry(QtCore.QRect(160, 40, 51, 25))
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.lineEdit_y = QtWidgets.QLineEdit(self.goal_group)
        self.lineEdit_y.setGeometry(QtCore.QRect(160, 80, 51, 25))
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.lineEdit_ang = QtWidgets.QLineEdit(self.goal_group)
        self.lineEdit_ang.setGeometry(QtCore.QRect(160, 120, 51, 25))
        self.lineEdit_ang.setObjectName("lineEdit_ang")
        self.buttonBox_joystick_2 = QtWidgets.QDialogButtonBox(self.goal_group)
        self.buttonBox_joystick_2.setGeometry(QtCore.QRect(100, 170, 169, 25))
        self.buttonBox_joystick_2.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox_joystick_2.setCenterButtons(True)
        self.buttonBox_joystick_2.setObjectName("buttonBox_joystick_2")
        self.label_x = QtWidgets.QLabel(self.goal_group)
        self.label_x.setGeometry(QtCore.QRect(100, 40, 45, 17))
        self.label_x.setObjectName("label_x")
        self.label_y = QtWidgets.QLabel(self.goal_group)
        self.label_y.setGeometry(QtCore.QRect(100, 80, 44, 17))
        self.label_y.setObjectName("label_y")
        self.label_deg = QtWidgets.QLabel(self.goal_group)
        self.label_deg.setGeometry(QtCore.QRect(40, 120, 107, 17))
        self.label_deg.setObjectName("label_deg")
        self.joystick_group = QtWidgets.QGroupBox(self.navigation)
        self.joystick_group.setGeometry(QtCore.QRect(540, 40, 361, 291))
        self.joystick_group.setAlignment(QtCore.Qt.AlignCenter)
        self.joystick_group.setObjectName("joystick_group")
        self.buttonBox_joystick = QtWidgets.QDialogButtonBox(self.joystick_group)
        self.buttonBox_joystick.setGeometry(QtCore.QRect(90, 40, 169, 25))
        self.buttonBox_joystick.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Open)
        self.buttonBox_joystick.setCenterButtons(True)
        self.buttonBox_joystick.setObjectName("buttonBox_joystick")
        self.textBrowser_joystick = QtWidgets.QTextBrowser(self.joystick_group)
        self.textBrowser_joystick.setGeometry(QtCore.QRect(30, 80, 281, 191))
        self.textBrowser_joystick.setObjectName("textBrowser_joystick")
        self.pushButton_2 = QtWidgets.QPushButton(self.navigation)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 330, 134, 42))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.navigation, "")
        self.arm = QtWidgets.QWidget()
        self.arm.setObjectName("arm")
        self.label = QtWidgets.QLabel(self.arm)
        self.label.setGeometry(QtCore.QRect(80, 60, 467, 425))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../../media/sf_Echange/arm-removebg-preview.png"))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.arm)
        self.groupBox.setGeometry(QtCore.QRect(480, 160, 141, 80))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.groupBox_2 = QtWidgets.QGroupBox(self.arm)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 151, 80))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.arm)
        self.groupBox_3.setGeometry(QtCore.QRect(170, 360, 141, 80))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.arm)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 500, 131, 80))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.groupBox_4)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(10, 40, 111, 16))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.arm)
        self.groupBox_5.setGeometry(QtCore.QRect(350, 30, 141, 80))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.line = QtWidgets.QFrame(self.arm)
        self.line.setGeometry(QtCore.QRect(623, 20, 20, 571))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_3 = QtWidgets.QPushButton(self.arm)
        self.pushButton_3.setGeometry(QtCore.QRect(750, 170, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.arm)
        self.pushButton_4.setGeometry(QtCore.QRect(750, 250, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.arm)
        self.pushButton_5.setGeometry(QtCore.QRect(750, 340, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.arm, "")
        self.server = QtWidgets.QWidget()
        self.server.setObjectName("server")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.server)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 80, 421, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_server = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_server.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_server.setObjectName("verticalLayout_server")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Start_server = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Start_server.setObjectName("Start_server")
        self.horizontalLayout.addWidget(self.Start_server)
        self.Stop_server = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Stop_server.setAutoDefault(False)
        self.Stop_server.setDefault(False)
        self.Stop_server.setFlat(False)
        self.Stop_server.setObjectName("Stop_server")
        self.horizontalLayout.addWidget(self.Stop_server)
        self.verticalLayout_server.addLayout(self.horizontalLayout)
        self.log_server = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.log_server.setObjectName("log_server")
        self.verticalLayout_server.addWidget(self.log_server)
        self.get_list = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.get_list.setAutoDefault(False)
        self.get_list.setObjectName("get_list")
        self.verticalLayout_server.addWidget(self.get_list)
        self.clear_list = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clear_list.setObjectName("clear_list")
        self.verticalLayout_server.addWidget(self.clear_list)
        self.get_last = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.get_last.setObjectName("get_last")
        self.verticalLayout_server.addWidget(self.get_last)
        self.remove_last = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.remove_last.setObjectName("remove_last")
        self.verticalLayout_server.addWidget(self.remove_last)
        self.tabWidget.addTab(self.server, "")
        self.camera = QtWidgets.QWidget()
        self.camera.setObjectName("camera")
        self.tabWidget.addTab(self.camera, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.horloge_group.setTitle(_translate("MainWindow", "Synchronisation des horloges"))
        self.pushButton.setText(_translate("MainWindow", "Synchronize"))
        self.Button_check_date.setText(_translate("MainWindow", "Check Date"))
        self.tf_odom_horloge.setTitle(_translate("MainWindow", "Lancer tf et odométrie"))
        self.button_launc_tf_odom.setText(_translate("MainWindow", "Launch"))
        self.label_status_tf_odom.setText(_translate("MainWindow", "Status: "))
        self.ssh_group.setTitle(_translate("MainWindow", "SSH jetauto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jetauto), _translate("MainWindow", "Jetauto"))
        self.cmdvel_group.setTitle(_translate("MainWindow", "cmd_vel control"))
        self.forward_but.setText(_translate("MainWindow", "Forward"))
        self.backward_but.setText(_translate("MainWindow", "Backward"))
        self.left_but.setText(_translate("MainWindow", "left"))
        self.right_but.setText(_translate("MainWindow", "right"))
        self.stop_but.setText(_translate("MainWindow", "STOP"))
        self.omni_left_but.setText(_translate("MainWindow", "Omni left"))
        self.omni_right_but.setText(_translate("MainWindow", "Omni right"))
        self.vitesse_label.setText(_translate("MainWindow", "Vitesse: "))
        self.label_vitesse_cmdvel.setText(_translate("MainWindow", "0"))
        self.amcl_group.setTitle(_translate("MainWindow", "position AMCL"))
        self.button_check_pose.setText(_translate("MainWindow", "check pose"))
        self.button_reset_pose.setText(_translate("MainWindow", "reset pose"))
        self.label_pose.setText(_translate("MainWindow", "Position:"))
        self.label_pose_amcl.setText(_translate("MainWindow", "0"))
        self.goal_group.setTitle(_translate("MainWindow", "Goal"))
        self.label_x.setText(_translate("MainWindow", "pos X: "))
        self.label_y.setText(_translate("MainWindow", "pos Y :"))
        self.label_deg.setText(_translate("MainWindow", "angle (degree): "))
        self.joystick_group.setTitle(_translate("MainWindow", "joystick"))
        self.pushButton_2.setText(_translate("MainWindow", "launch Move_Base \n"
" & Rviz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.navigation), _translate("MainWindow", "navigation"))
        self.groupBox.setTitle(_translate("MainWindow", "Joint 3"))
        self.groupBox_2.setTitle(_translate("MainWindow", "r_joint (gripper)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Joint 2"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Joint 1"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Joint 4"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.arm), _translate("MainWindow", "arm"))
        self.Start_server.setText(_translate("MainWindow", "Start server"))
        self.Stop_server.setText(_translate("MainWindow", "Stop server"))
        self.get_list.setText(_translate("MainWindow", "Get list"))
        self.clear_list.setText(_translate("MainWindow", "Clear list"))
        self.get_last.setText(_translate("MainWindow", "Get_last"))
        self.remove_last.setText(_translate("MainWindow", "Remove last"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.server), _translate("MainWindow", "server flask"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.camera), _translate("MainWindow", "camera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

