local_costmap:
  global_frame: odom                 # Cadre de référence pour la carte locale
  robot_base_frame: base_footprint   # Cadre de référence du robot
  update_frequency: 10.0             # Fréquence de mise à jour élevée (20 Hz)
  publish_frequency: 10.0            # Fréquence de publication élevée (20 Hz)
  rolling_window: true               # Fenêtre mobile activée (suivi du robot)
  width: 3.0                         
  height: 3.0                        
  resolution: 0.025                  # Haute résolution (2,5 cm par cellule)
  transform_tolerance: 1             # Tolérance de transformation élevée (5s)
  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer:
    enabled: true
    inflation_radius: 0.3  # Doit être ≥ au rayon du robot
    cost_scaling_factor: 1  # Facteur d'échelle du coût
  virtual_wall:
    map_frame: "map"
