gazebo_ros_control:
  pid_gains:
    joint1: {p: 100.0, i: 0.01, d: 1.0}
    joint2: {p: 100.0, i: 0.01, d: 1.0}
    joint3: {p: 100.0, i: 0.01, d: 1.0}
    joint4: {p: 100.0, i: 0.01, d: 1.0}
    joint5: {p: 100.0, i: 0.01, d: 1.0}
    r_joint: {p: 50.0, i: 0.01, d: 0.5}
